// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cookie_stand_api.Data;

#nullable disable

namespace cookie_stand_api.Migrations
{
    [DbContext(typeof(CookiesStandDbContext))]
    partial class CookiesStandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cookie_stand_api.Models.Entites.CookieStand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("average_cookies_per_sale")
                        .HasColumnType("float");

                    b.Property<int>("maximum_customers_per_hour")
                        .HasColumnType("int");

                    b.Property<int>("minimum_customers_per_hour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CookieStands");
                });

            modelBuilder.Entity("cookie_stand_api.Models.Entites.HourlySales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookieStandid")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CookieStandid");

                    b.ToTable("HourSales");
                });

            modelBuilder.Entity("cookie_stand_api.Models.Entites.HourlySales", b =>
                {
                    b.HasOne("cookie_stand_api.Models.Entites.CookieStand", null)
                        .WithMany("Hourly_sales")
                        .HasForeignKey("CookieStandid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cookie_stand_api.Models.Entites.CookieStand", b =>
                {
                    b.Navigation("Hourly_sales");
                });
#pragma warning restore 612, 618
        }
    }
}
